### ISSUE TITLE
Test not passing on gitlab

### ISSUE THREAD

**Issue by aboellinger** [cgwire/zou#191]
After rebasing our fork on the official master branch we still get 2 tests failing (on our gitlab server)

## Gitlab CI file

```
stages:
  - test

tests:python:
  stage: test
  image: python:3
  services:
    - postgres:9
  variables:
    AUTH_STRATEGY: auth_local_no_password
    DB_HOST: postgres
    POSTGRES_DB: zoudb
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: postgres
    PREVIEW_FOLDER: ./data
  script:
    # Create thumbnail folder
    - mkdir -p $PREVIEW_FOLDER

    # Install pg_dump
    - apt-get update
    - apt-get install postgresql-client --yes

    # Install requirements
    - pip install -r requirements.txt

    # Run Tests
    - PYTHONPATH=. py.test --ignore=tests/auth/test_auth_route.py
  tags:
    - test
```

## pytest fail report

```
=================================== FAILURES ===================================
___________________ RouteThumbnailTestCase.test_add_preview ____________________

self = <tests.thumbnails.test_route_thumbnail.RouteThumbnailTestCase testMethod=test_add_preview>

    def test_add_preview(self):
        path = "/pictures/preview-files/%s" % self.preview_file_id
    
        file_path_fixture = self.get_fixture_file_path(
                os.path.join("thumbnails", "th01.png"))
        self.upload_file(path, file_path_fixture)
    
        current_path = os.path.dirname(__file__)
        result_file_path = os.path.join(TEST_FOLDER, "th01.png")
        result_file_path = os.path.join(
            current_path, "..", "..", result_file_path)
        os.mkdir(TEST_FOLDER)
    
        path = "/pictures/previews/preview-files/%s.png" % self.preview_file_id
>       self.download_file(path, result_file_path)

tests/thumbnails/test_route_thumbnail.py:81: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/base.py:205: in download_file
    self.assertEqual(response.status_code, code)
E   AssertionError: 404 != 200
----------------------------- Captured stdout call -----------------------------
2019-10-11 15:30:26,560 - ERROR - [Errno 2] No such file or directory: '/builds/antoine.boellinger/zou/zou/app/./data/pictures/previews/177/e12/177e12fd-14f4-4de4-9ba9-3606f04cb2e7'
------------------------------ Captured log call -------------------------------
ERROR    zou.app:resources.py:120 [Errno 2] No such file or directory: '/builds/antoine.boellinger/zou/zou/app/./data/pictures/previews/177/e12/177e12fd-14f4-4de4-9ba9-3606f04cb2e7'
__________________ RouteThumbnailTestCase.test_add_thumbnail ___________________

self = <tests.thumbnails.test_route_thumbnail.RouteThumbnailTestCase testMethod=test_add_thumbnail>

    def test_add_thumbnail(self):
        path = "/pictures/thumbnails/persons/%s" % self.person.id
    
        file_path_fixture = self.get_fixture_file_path(
                os.path.join("thumbnails", "th01.png"))
        self.upload_file(path, file_path_fixture)
    
        path = "/pictures/thumbnails/persons/%s.png" % self.person.id
        current_path = os.path.dirname(__file__)
        result_file_path = os.path.join(TEST_FOLDER, "th01.png")
        result_file_path = os.path.join(
            current_path, "..", "..", result_file_path)
    
        os.mkdir(TEST_FOLDER)
>       self.download_file(path, result_file_path)

tests/thumbnails/test_route_thumbnail.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/base.py:205: in download_file
    self.assertEqual(response.status_code, code)
E   AssertionError: 404 != 200
----------------------------- Captured stdout call -----------------------------
2019-10-11 15:30:28,906 - ERROR - [Errno 2] No such file or directory: '/builds/antoine.boellinger/zou/zou/app/./data/pictures/thumbnails/62a/e43/62ae436a-40a5-4521-b816-984cd3a369b3'
------------------------------ Captured log call -------------------------------
ERROR    zou.app:resources.py:120 [Errno 2] No such file or directory: '/builds/antoine.boellinger/zou/zou/app/./data/pictures/thumbnails/62a/e43/62ae436a-40a5-4521-b816-984cd3a369b3'
```

Any idea on what could cause this issue ?
