### ISSUE TITLE
Docker - Cannot access to the required Redis instance

### ISSUE THREAD

**Issue by paullam328** [cgwire/zou#440]
I need to host my Zou instance in a container at port 5000 in order to properly deploy Blender Watchtower in another container, in which a part of its code makes api calls to port 5000 to authenticate users: https://studio.blender.org/blog/introducing-watchtower. (Posted gunicorn, zou and nginx config files in the following comment)

Dockerfile:
```
FROM ubuntu:latest

#  Install third parties software:
RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get install -y postgresql \
    postgresql-client \
    postgresql-server-dev-all \
    redis-server \
    python3.7 \
    python3-pip \
    git \
    nginx \
    ffmpeg

# Create zou user:
RUN useradd --home /opt/zou zou && \
    mkdir /opt/zou && \
    chown zou: /opt/zou && \
    mkdir /opt/zou/backups && \
    chown zou: /opt/zou/backups && \
    mkdir /opt/zou/logs && \
    chown zou: /opt/zou/logs

# Install Zou and its dependencies:
RUN pip3 install virtualenv && \
    cd /opt/zou && \
    virtualenv zouenv && \
    . zouenv/bin/activate && \
    zouenv/bin/pip3 install zou && \
    chown -R zou:www-data .

# Create a folder to store the previews:
RUN mkdir /opt/zou/previews && \
    chown -R zou:www-data /opt/zou

# Create a folder to store the previews:
RUN mkdir /opt/zou/tmp && \
    chown -R zou:www-data /opt/zou/tmp

# Create Zou database in postgres:
USER postgres

RUN service postgresql start && \
    psql --command "create database zoudb;" -U postgres && \
    psql --command "ALTER USER postgres WITH PASSWORD 'mysecretpassword';"

USER root
WORKDIR /opt/zou

# Configure Guincorn Main API server:
RUN mkdir /etc/zou
COPY gunicorn.conf /etc/zou
COPY zou.service /etc/systemd/system

# Configure Events Stream API server:
COPY gunicorn-events.conf /etc/zou
COPY zou-events.service /etc/systemd/system

# Configure Nginx:
COPY nginx /etc/nginx/sites-available
RUN rm /etc/nginx/sites-enabled/default && \
    ln -s /etc/nginx/sites-available/nginx /etc/nginx/sites-enabled

# Start our daemon and restart Nginx
# RUN systemctl enable zou && \
#     systemctl enable zou-events && \
#     service nginx restart

ENV DB_PASSWORD=mysecretpassword
ENV SECRET_KEY=yourrandomsecretkey
ENV PATH=/opt/zou/zouenv/bin
ENV PREVIEW_FOLDER=/opt/zou/previews
ENV TMP_DIR=/opt/zou/tmp

# for sh debugging purposes:
# RUN apk update
# RUN apk add

RUN /opt/zou/zouenv/bin/gunicorn -c /etc/zou/gunicorn.conf -b 0.0.0.0:5000 zou.app:app && \
    # /opt/zou/zouenv/bin/gunicorn -c /etc/zou/gunicorn-events.conf -b 0.0.0.0:5001 zou.event_stream:app && \
    service nginx restart
```

docker-compose.yml:

```
version: '3.2'

services:

  zou-cgwire:
    build:
      context: ./docker-cgwire-solo
      dockerfile: ./Dockerfile
    container_name: cgwire
    ports:
      - 80:80
    # networks:
    #   - redis_network
    depends_on:
      - redis
    # environment:
    #   - REDIS_HOST=redis
```

Somehow, after building the Zou instance, I got a spam of errors within the instance:
"Cannot access to the required Redis instance"

So, I try to add the line below to docker-compose.yml, in order to deploy a Redis instance in a separate contaniner:
```
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server
```

I think I've tried adding them to the same Docker network as well, still doesn't work.  Have been figuring this out for days.  Would be nice if anyone can help thanks!
